Bookstore: styling
Oscah01/book-store pull request #6
Opened 2023-03-09 22:32 UTC by Oscah01

- Add missing jsx elements (without adding extra functionality)
- add styling

2023-03-09 23:19 UTC, DuaneDave requested changes
Hi @Oscah01  👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Correct usage of workflows
✔️ No linter error
✔️ PR summary is descriptive

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 23:19 UTC, DuaneDave commented on src/pages/Books.jsx
> +      </div>
The styling of the app is still not matching the Zeplin design except i zoom out to 80%, I have circled out some parts of your design that is not consistent with Zeplin. Please work on the design to make your app more visually appealing.


YOUR DESIGN

![bsdcomplete](https://user-images.githubusercontent.com/84930355/224181229-999e5f47-c3ec-404b-b0e7-41ba42e69896.PNG)

ZEPLIN DESIGN

![incomplete](https://user-images.githubusercontent.com/84930355/224181294-fb243a99-aa60-4e55-85f4-091ca194d5d6.PNG)

2023-03-10 10:24 UTC, levy002 requested changes
## Hello @Oscah01   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 10:24 UTC, levy002 commented on src/index.css
> +}
- [ ] As requeted by the previous reviewer, Kindly make sure to stick to the provided Figma design. Please make sure the `BOOK STORE` title is aligned on the same starting vertical line with the booklist and form on the page as previously shown on the designs.

   - ### YOUR DESIGN
   
    ![image](https://user-images.githubusercontent.com/87197412/224291309-3dad9cf9-f151-4d7c-8e50-2759e01ce29e.png)

   - ### FIGMA DESIGN
   
     ![image](https://user-images.githubusercontent.com/87197412/224291593-cf9a131f-b850-4394-92bb-e896a46d6bfa.png)

2023-03-10 11:07 UTC, merged